### ISSUE TITLE
Cannot install on mac

### ISSUE THREAD

**Issue by jjyr** [conformal/gotk3#69]
I run the command: 
go get -v github.com/conformal/gotk3/gdkgithub.com/conformal/gotk3/glib

output below:

```
# github.com/conformal/gotk3/glib
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x15672]

goroutine 16 [running]:
runtime.panic(0x1dae60, 0x31b9e4)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
main.(*typeConv).Type(0x2083b8420, 0x22083859f0, 0x2083ef530, 0xaf94, 0x2208382601)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1288 +0x1632
main.(*typeConv).Type(0x2083b8420, 0x22083859b8, 0x2083ef4d0, 0xaf94, 0x0)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1189 +0x3dd6
main.(*typeConv).Struct(0x2083b8420, 0x2083731a0, 0xaf94, 0x6, 0x0, 0x0, 0x8)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1551 +0x70b
main.(*typeConv).Type(0x2083b8420, 0x2208385af8, 0x2083731a0, 0xaf94, 0x2085b52e0)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1234 +0x3038
main.(*typeConv).Type(0x2083b8420, 0x22083859f0, 0x2083ef3e0, 0xaf94, 0x26d401)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1269 +0x1301
main.(*typeConv).Type(0x2083b8420, 0x22083859b8, 0x2083ef350, 0xaf94, 0x4)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1189 +0x3dd6
main.(*typeConv).Struct(0x2083b8420, 0x208372ae0, 0xaf94, 0x6, 0x0, 0x0, 0x8)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1551 +0x70b
main.(*typeConv).Type(0x2083b8420, 0x2208385af8, 0x208372ae0, 0xaf94, 0x2085b5050)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1234 +0x3038
main.(*typeConv).Type(0x2083b8420, 0x22083859f0, 0x20840be60, 0xaf94, 0x2208376801)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1269 +0x1301
main.(*typeConv).Type(0x2083b8420, 0x22083859b8, 0x20840be00, 0xaf94, 0x4)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1189 +0x3dd6
main.(*typeConv).FuncArg(0x2083b8420, 0x22083859b8, 0x20840be00, 0xaf94, 0x1)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1405 +0x59
main.(*typeConv).FuncType(0x2083b8420, 0x2083ebbc0, 0xaf94, 0x2083ebbc0)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:1458 +0x534
main.(*Package).loadDWARF(0x20836f2b0, 0x2083b6180, 0x20841a800, 0x100, 0x100)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:539 +0x1462
main.(*Package).Translate(0x20836f2b0, 0x2083b6180)
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/gcc.go:182 +0x150
main.main()
    /usr/local/Cellar/go/1.3/libexec/src/cmd/cgo/main.go:259 +0xef1

goroutine 19 [finalizer wait]:
runtime.park(0x4fed0, 0x31feb8, 0x31f269)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x31feb8, 0x31f269)
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/Cellar/go/1.3/libexec/src/pkg/runtime/proc.c:1445
```

**Comment by jrick** [comment]
Go 1.3 cgo has a bug where it panics when go was built with clang.  It's fixed in go tip and on the 1.3 release branch.  Either downgrade to 1.2, build tip, or wait for 1.3.1.
